version: "3.3"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: password # environment variable that sets the superuser password for PostgreSQL
      POSTGRES_USER: user # variable that will create the specified user with superuser power and a database with the same name
      POSTGRES_DB: zeply2
      POSTGRES_HOST: db
      container_name: db
      hostname: db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # - ./scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5434:5434"
    expose:
      - "5434"

  web:
    build: .
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8080:5000"
    expose:
      - "5000"

volumes:
  postgres_data:
